//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.WorkFlowService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WorkFlowService.IWorkFlow")]
    public interface IWorkFlow {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkFlow/GetWorkFlowDocuments", ReplyAction="http://tempuri.org/IWorkFlow/GetWorkFlowDocumentsResponse")]
        Alfanet.CommonObject.ObjWorkFlowDocuments GetWorkFlowDocuments(Alfanet.CommonObject.ConfigData config, string CodigoDependencia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkFlow/GetDependencias", ReplyAction="http://tempuri.org/IWorkFlow/GetDependenciasResponse")]
        Alfanet.CommonObject.ObjDependencia[] GetDependencias(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkFlow/GetAcciones", ReplyAction="http://tempuri.org/IWorkFlow/GetAccionesResponse")]
        Alfanet.CommonObject.ObjAccion[] GetAcciones(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWorkFlow/RedirectDocument", ReplyAction="http://tempuri.org/IWorkFlow/RedirectDocumentResponse")]
        string RedirectDocument(string document, string dependenciaDestino, string note, string dependenciaOrigen, string accion, Alfanet.CommonObject.ConfigData config);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWorkFlowChannel : WebApplication1.WorkFlowService.IWorkFlow, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkFlowClient : System.ServiceModel.ClientBase<WebApplication1.WorkFlowService.IWorkFlow>, WebApplication1.WorkFlowService.IWorkFlow {
        
        public WorkFlowClient() {
        }
        
        public WorkFlowClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkFlowClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Alfanet.CommonObject.ObjWorkFlowDocuments GetWorkFlowDocuments(Alfanet.CommonObject.ConfigData config, string CodigoDependencia) {
            return base.Channel.GetWorkFlowDocuments(config, CodigoDependencia);
        }
        
        public Alfanet.CommonObject.ObjDependencia[] GetDependencias(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetDependencias(config);
        }
        
        public Alfanet.CommonObject.ObjAccion[] GetAcciones(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetAcciones(config);
        }
        
        public string RedirectDocument(string document, string dependenciaDestino, string note, string dependenciaOrigen, string accion, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.RedirectDocument(document, dependenciaDestino, note, dependenciaOrigen, accion, config);
        }
    }
}
