//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.DocumentosFisicosService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DocumentosFisicosService.IDocumentosFisicos")]
    public interface IDocumentosFisicos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentosFisicos/GetPendingDocuments", ReplyAction="http://tempuri.org/IDocumentosFisicos/GetPendingDocumentsResponse")]
        Alfanet.CommonObject.ObjDocumentos[] GetPendingDocuments(Alfanet.CommonObject.ConfigData config, string dependenciaCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentosFisicos/DocumentAccepted", ReplyAction="http://tempuri.org/IDocumentosFisicos/DocumentAcceptedResponse")]
        bool DocumentAccepted(Alfanet.CommonObject.ConfigData config, string numeroDocumento, string grupoCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDocumentosFisicos/GetReceivedDocuments", ReplyAction="http://tempuri.org/IDocumentosFisicos/GetReceivedDocumentsResponse")]
        Alfanet.CommonObject.ObjDocumentos[] GetReceivedDocuments(out string resultado, string fechaInicial, string fechaFinal, string dependenciaCodigo, Alfanet.CommonObject.ConfigData config);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDocumentosFisicosChannel : WebApplication1.DocumentosFisicosService.IDocumentosFisicos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentosFisicosClient : System.ServiceModel.ClientBase<WebApplication1.DocumentosFisicosService.IDocumentosFisicos>, WebApplication1.DocumentosFisicosService.IDocumentosFisicos {
        
        public DocumentosFisicosClient() {
        }
        
        public DocumentosFisicosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DocumentosFisicosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentosFisicosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DocumentosFisicosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Alfanet.CommonObject.ObjDocumentos[] GetPendingDocuments(Alfanet.CommonObject.ConfigData config, string dependenciaCodigo) {
            return base.Channel.GetPendingDocuments(config, dependenciaCodigo);
        }
        
        public bool DocumentAccepted(Alfanet.CommonObject.ConfigData config, string numeroDocumento, string grupoCodigo) {
            return base.Channel.DocumentAccepted(config, numeroDocumento, grupoCodigo);
        }
        
        public Alfanet.CommonObject.ObjDocumentos[] GetReceivedDocuments(out string resultado, string fechaInicial, string fechaFinal, string dependenciaCodigo, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetReceivedDocuments(out resultado, fechaInicial, fechaFinal, dependenciaCodigo, config);
        }
    }
}
