//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.ErrorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ErrorService.IError")]
    public interface IError {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IError/SaveLogError", ReplyAction="http://tempuri.org/IError/SaveLogErrorResponse")]
        bool SaveLogError(Alfanet.CommonObject.ObjError Error, Alfanet.CommonObject.ConfigData config);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IErrorChannel : WebApplication1.ErrorService.IError, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ErrorClient : System.ServiceModel.ClientBase<WebApplication1.ErrorService.IError>, WebApplication1.ErrorService.IError {
        
        public ErrorClient() {
        }
        
        public ErrorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ErrorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ErrorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool SaveLogError(Alfanet.CommonObject.ObjError Error, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.SaveLogError(Error, config);
        }
    }
}
