//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.RadicacionMasivaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RadicacionMasivaService.IRadicacionMasiva")]
    public interface IRadicacionMasiva {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetPreview", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetPreviewResponse")]
        Alfanet.CommonObject.ObjFactura[] GetPreview(out string[] result, out string objCacheName, out string summary, out string CamposVacios, out string DuplicadosDB, out string DuplicadosExcel, string dependenciaEnvio, string naturaleza, string medio, string CodDep, Alfanet.CommonObject.ConfigData config, byte[] file, string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetParametrosIniciales", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetParametrosInicialesResponse")]
        Alfanet.CommonObject.ObjParametros[] GetParametrosIniciales(string grupoCodigo, Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetNaturalezas", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetNaturalezasResponse")]
        Alfanet.CommonObject.ObjNaturaleza[] GetNaturalezas(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetDependencias", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetDependenciasResponse")]
        Alfanet.CommonObject.ObjDependencia[] GetDependencias(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetAcciones", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetAccionesResponse")]
        Alfanet.CommonObject.ObjAccion[] GetAcciones(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetMedios", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetMediosResponse")]
        Alfanet.CommonObject.ObjMedio[] GetMedios(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetExpedientes", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetExpedientesResponse")]
        Alfanet.CommonObject.ObjExpediente[] GetExpedientes(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/RadicarFacturas", ReplyAction="http://tempuri.org/IRadicacionMasiva/RadicarFacturasResponse")]
        Alfanet.CommonObject.ObjFactura[] RadicarFacturas(out string result, string UserID, string nomDep, string Dependencia, string ObjCacheName, string tempImagesPath, Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/BuscarRadicados", ReplyAction="http://tempuri.org/IRadicacionMasiva/BuscarRadicadosResponse")]
        Alfanet.CommonObject.ObjFactura[] BuscarRadicados(
                    string Radicador, 
                    string porImagen, 
                    long radInicial, 
                    long radFinal, 
                    string comEgresoIni, 
                    string comEgresoFin, 
                    string fechaInicial, 
                    string fechaFinal, 
                    string FacnReciboIni, 
                    string FacnReciboFin, 
                    string facValorMenor, 
                    string facValorMayor, 
                    string numFacIni, 
                    string numFacFinal, 
                    string nombreNit, 
                    string detalle, 
                    string ubicacion, 
                    string modalidad, 
                    string unidad, 
                    string expediente, 
                    string ciudadInicial, 
                    string ciudadFinal, 
                    Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/ObtenerDatosDependencia", ReplyAction="http://tempuri.org/IRadicacionMasiva/ObtenerDatosDependenciaResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="UserIdAlfa")]
        string ObtenerDatosDependencia(out string NombreDependencia, string Dependencia, Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/ValidateFiles", ReplyAction="http://tempuri.org/IRadicacionMasiva/ValidateFilesResponse")]
        string[] ValidateFiles(out string result, string path, string cacheName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/ClearTempImages", ReplyAction="http://tempuri.org/IRadicacionMasiva/ClearTempImagesResponse")]
        bool ClearTempImages(out string result, string path);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/ValidarUsuarioPermitido", ReplyAction="http://tempuri.org/IRadicacionMasiva/ValidarUsuarioPermitidoResponse")]
        bool ValidarUsuarioPermitido(string Dependencia, Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/UpdateRadicado", ReplyAction="http://tempuri.org/IRadicacionMasiva/UpdateRadicadoResponse")]
        string UpdateRadicado(string codigo, string detalle, string[] compEgresoList, Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/LoadFromCache", ReplyAction="http://tempuri.org/IRadicacionMasiva/LoadFromCacheResponse")]
        Alfanet.CommonObject.ObjFactura[] LoadFromCache(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetCiudades", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetCiudadesResponse")]
        Alfanet.CommonObject.ObjCiudad[] GetCiudades(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetProcedencias", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetProcedenciasResponse")]
        Alfanet.CommonObject.ObjProcedencia[] GetProcedencias(Alfanet.CommonObject.ConfigData config);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRadicacionMasiva/GetResultadosBusqueda", ReplyAction="http://tempuri.org/IRadicacionMasiva/GetResultadosBusquedaResponse")]
        Alfanet.CommonObject.ObjFactura[] GetResultadosBusqueda(string nombre);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRadicacionMasivaChannel : WebApplication1.RadicacionMasivaService.IRadicacionMasiva, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RadicacionMasivaClient : System.ServiceModel.ClientBase<WebApplication1.RadicacionMasivaService.IRadicacionMasiva>, WebApplication1.RadicacionMasivaService.IRadicacionMasiva {
        
        public RadicacionMasivaClient() {
        }
        
        public RadicacionMasivaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RadicacionMasivaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RadicacionMasivaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RadicacionMasivaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Alfanet.CommonObject.ObjFactura[] GetPreview(out string[] result, out string objCacheName, out string summary, out string CamposVacios, out string DuplicadosDB, out string DuplicadosExcel, string dependenciaEnvio, string naturaleza, string medio, string CodDep, Alfanet.CommonObject.ConfigData config, byte[] file, string fileName) {
            return base.Channel.GetPreview(out result, out objCacheName, out summary, out CamposVacios, out DuplicadosDB, out DuplicadosExcel, dependenciaEnvio, naturaleza, medio, CodDep, config, file, fileName);
        }
        
        public Alfanet.CommonObject.ObjParametros[] GetParametrosIniciales(string grupoCodigo, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetParametrosIniciales(grupoCodigo, config);
        }
        
        public Alfanet.CommonObject.ObjNaturaleza[] GetNaturalezas(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetNaturalezas(config);
        }
        
        public Alfanet.CommonObject.ObjDependencia[] GetDependencias(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetDependencias(config);
        }
        
        public Alfanet.CommonObject.ObjAccion[] GetAcciones(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetAcciones(config);
        }
        
        public Alfanet.CommonObject.ObjMedio[] GetMedios(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetMedios(config);
        }
        
        public Alfanet.CommonObject.ObjExpediente[] GetExpedientes(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetExpedientes(config);
        }
        
        public Alfanet.CommonObject.ObjFactura[] RadicarFacturas(out string result, string UserID, string nomDep, string Dependencia, string ObjCacheName, string tempImagesPath, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.RadicarFacturas(out result, UserID, nomDep, Dependencia, ObjCacheName, tempImagesPath, config);
        }
        
        public Alfanet.CommonObject.ObjFactura[] BuscarRadicados(
                    string Radicador, 
                    string porImagen, 
                    long radInicial, 
                    long radFinal, 
                    string comEgresoIni, 
                    string comEgresoFin, 
                    string fechaInicial, 
                    string fechaFinal, 
                    string FacnReciboIni, 
                    string FacnReciboFin, 
                    string facValorMenor, 
                    string facValorMayor, 
                    string numFacIni, 
                    string numFacFinal, 
                    string nombreNit, 
                    string detalle, 
                    string ubicacion, 
                    string modalidad, 
                    string unidad, 
                    string expediente, 
                    string ciudadInicial, 
                    string ciudadFinal, 
                    Alfanet.CommonObject.ConfigData config) {
            return base.Channel.BuscarRadicados(Radicador, porImagen, radInicial, radFinal, comEgresoIni, comEgresoFin, fechaInicial, fechaFinal, FacnReciboIni, FacnReciboFin, facValorMenor, facValorMayor, numFacIni, numFacFinal, nombreNit, detalle, ubicacion, modalidad, unidad, expediente, ciudadInicial, ciudadFinal, config);
        }
        
        public string ObtenerDatosDependencia(out string NombreDependencia, string Dependencia, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.ObtenerDatosDependencia(out NombreDependencia, Dependencia, config);
        }
        
        public string[] ValidateFiles(out string result, string path, string cacheName) {
            return base.Channel.ValidateFiles(out result, path, cacheName);
        }
        
        public bool ClearTempImages(out string result, string path) {
            return base.Channel.ClearTempImages(out result, path);
        }
        
        public bool ValidarUsuarioPermitido(string Dependencia, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.ValidarUsuarioPermitido(Dependencia, config);
        }
        
        public string UpdateRadicado(string codigo, string detalle, string[] compEgresoList, Alfanet.CommonObject.ConfigData config) {
            return base.Channel.UpdateRadicado(codigo, detalle, compEgresoList, config);
        }
        
        public Alfanet.CommonObject.ObjFactura[] LoadFromCache(string nombre) {
            return base.Channel.LoadFromCache(nombre);
        }
        
        public Alfanet.CommonObject.ObjCiudad[] GetCiudades(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetCiudades(config);
        }
        
        public Alfanet.CommonObject.ObjProcedencia[] GetProcedencias(Alfanet.CommonObject.ConfigData config) {
            return base.Channel.GetProcedencias(config);
        }
        
        public Alfanet.CommonObject.ObjFactura[] GetResultadosBusqueda(string nombre) {
            return base.Channel.GetResultadosBusqueda(nombre);
        }
    }
}
